# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'lacledeslan/gamesvr-csgo-tourney'

steps:
# DEPENDENCIES
- script: docker pull lacledeslan/gamesvr-csgo
  displayName: 'Fetch image lacledeslan/gamesvr-csgo'
- script: docker pull lacledeslan/sourceseer
  displayName: 'Fetch image lacledeslan/sourceseer'
- script: docker login -u $(dockerUser) -p $(dockerPass)
  displayName: 'docker hub login'
# LATEST
- script: docker build . -f linux.Dockerfile -t lacledeslan/gamesvr-csgo-tourney --no-cache --build-arg BUILDNODE=Azure;
  displayName: 'latest - Docker Build'
- script: docker run --rm --entrypoint "/bin/bash" lacledeslan/gamesvr-csgo-tourney ./ll-tests/gamesvr-csgo-tourney.sh;
  displayName: 'latest - Run Self Tests'
- script: docker push lacledeslan/gamesvr-csgo-tourney
  displayName: 'latest - Push to Docker HUB'
# HASTY
- script: docker build . -f linux.hasty.Dockerfile -t lacledeslan/gamesvr-csgo-tourney:hasty --no-cache --build-arg BUILDNODE=Azure;
  displayName: 'hasty - Docker Build'
- script: docker push lacledeslan/gamesvr-csgo-tourney:hasty
  displayName: 'hasty - Push to Docker HUB'
# OVERTIME
- script: docker build . -f linux.overtime.Dockerfile -t lacledeslan/gamesvr-csgo-tourney:overtime --no-cache --build-arg BUILDNODE=Azure;
  displayName: 'overtime - Docker Build'
- script: docker push lacledeslan/gamesvr-csgo-tourney:overtime
  displayName: 'overtime - Push to Docker HUB'
# META
- script: curl -X POST  "https://hooks.microbadger.com/images/lacledeslan/gamesvr-csgo-tourney/$(microBadgerToken)"
  displayName: 'latest - Update MicroBadger'
# CLEAN UP
- script: docker logout
  displayName: 'Log out of Docker HUB'
